apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: controlcenter
  namespace: operator
spec:
  replicas: 1
  image:
    application: confluentinc/cp-enterprise-control-center:6.2.0
    init: confluentinc/confluent-init-container:2.1.0
  dataVolumeCapacity: 2Gi
  dependencies:
    schemaRegistry:
      url: http://schemaregistry.operator.svc.cluster.local:8081
    connect:
    - name: connect
      url: http://connect.operator.svc.cluster.local:8083
  podTemplate:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: NotIn
              values:
              - k3d-ievent-server-0