apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: operator
spec:
  replicas: 3
  oneReplicaPerNode: true
  podTemplate:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: "kubernetes.io/hostname"
              operator: NotIn
              values: 
              - "k3d-ievent-server-0"
  image:
    application: confluentinc/cp-server:6.2.0
    init: confluentinc/confluent-init-container:2.1.0
  dataVolumeCapacity: 3Gi
  metricReporter:
    enabled: true
