apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: my-first-connector
  namespace: operator
spec:
  name: my-first-connector
  class: FileStreamSink
  taskMax: 1
  connectClusterRef: 
    name: connect
    namespace: operator
  configs: 
    topics: my-first-topic
    file: /tmp/test-sink.txt
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.storage.StringConverter
  